Ref: updated create use ansible playbook

diff --git a/cloud/aws-main-infra/ansible/roles/wireguard-user/tasks/main.yml b/cloud/aws-main-infra/ansible/roles/wireguard-user/tasks/main.yml
--- a/cloud/aws-main-infra/ansible/roles/wireguard-user/tasks/main.yml
+++ b/cloud/aws-main-infra/ansible/roles/wireguard-user/tasks/main.yml
@@ -30,8 +30,8 @@
       NC='\033[0m' 
 
       if [[ $EUID -ne 0 ]]; then
-         echo -e "${RED}Error: This script must be run as root${NC}"
-         exit 1
+          echo -e "${RED}Error: This script must be run as root${NC}"
+          exit 1
       fi
 
       USERNAME=$1
